### ISSUE TITLE
Chore: Release WCA Test Helper version 0.7.0

### ISSUE THREAD

**Issue by mattsherman** [woocommerce/woocommerce-admin-test-helper#35]
We should release version 0.7.0 of WooCommerce Admin Test Helper in order to include new functionality since version 0.6.3, namely...

- https://github.com/woocommerce/woocommerce-admin-test-helper/pull/34

## Tasks

- [ ] Follow [steps to deploy](https://github.com/woocommerce/woocommerce-admin-test-helper#readme)

**Comment by octaedro** [comment]
WCA Test Helper 0.7.0 [has been released](https://github.com/woocommerce/woocommerce-admin-test-helper/releases/tag/v0.7.0) 🎉 🎉
